# This Deployment manages the pods for our Status Page application.
# It links the container to our ConfigMap, Secret, and ServiceAccount.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: status-page
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: status-page
  template:
    metadata:
      labels:
        app: status-page
    spec:
      # Attach the IAM role for S3 access
      serviceAccountName: {{ .Release.Name }}-sa
      containers:
        - name: status-page-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            # Inject non-secret variables from the ConfigMap
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          env:
            - name: DB_USER
              value: {{ .Values.database.user | quote }}
            # Inject the secret generated by External Secrets
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: DB_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: SECRET_KEY      

            # Injecting resources dynamically from values.yaml using the toYaml function
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          
          # Liveness Probe reading values from the probes section in values.yaml
          livenessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            # Dynamically pull the timeout value
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          
          # Readiness Probe reading values from the probes section in values.yaml
          readinessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            # Dynamically pull the timeout value
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}     