# This ExternalSecret fetches the password from AWS and dynamically creates a Kubernetes Secret.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-password-external
spec:
  # How often to check AWS for updates to the password
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    # This is the name of the actual Secret that will be injected into our pods
    name: {{ .Release.Name }}-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        # The exact name of the secret we created earlier in AWS Secrets Manager
        key: ofek-status-page/db-password
        property: DB_PASSWORD 
    - secretKey: SECRET_KEY
      remoteRef:
        key: ofek-status-page/db-password
        property: SECRET_KEY 