# Define the Ingress resource to expose our application to the internet
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}

spec:
  # This is the magic word that was missing! It tells the AWS controller to process this Ingress.
  ingressClassName: alb
  rules:
    - host: {{ .Values.ingress.host }}
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: 80