# This SecretStore tells the External Secrets Operator how to connect to AWS.
# It automatically uses the IAM role attached to the EKS worker nodes.
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: status-page-prod-sa