# This ServiceAccount provides an AWS identity to our application pods.
# It uses IRSA (IAM Roles for Service Accounts) to securely access AWS services like S3.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  labels:
    app: status-page
  annotations:
    # The actual IAM Role ARN we just created in Terraform for S3 access
    eks.amazonaws.com/role-arn: "arn:aws:iam::992382545251:role/ofek-status-page-app-s3-role"