# Default configuration values for the Status Page application.
# These values will be injected into our Kubernetes templates.

# Number of pod replicas we want running for high availability
replicaCount: 2

# Docker image details from Amazon ECR
image:
  repository: "992382545251.dkr.ecr.us-east-1.amazonaws.com/ofek-status-page-repo"
  pullPolicy: Always
  tag: "ca11fa11888b7245096eaca0594e92a71f37ab50"


# PostgreSQL Database (RDS) configuration
database:
  host: "ofek-status-page-rds.cx248m4we6k7.us-east-1.rds.amazonaws.com"
  port: "5432"
  name: "statuspagedb"
  user: "statuspage"

# Redis Cache (ElastiCache) configuration
redis:
  host: "ofek-status-page-redis.7fftml.0001.use1.cache.amazonaws.com"
  port: "6379"

# S3 Bucket configuration for static assets
s3:
  bucketName: "ofek-status-page-assets-bucket-8849"
  region: "us-east-1"

# Internal service port for the application
service:
  port: 8001

  # Defining CPU and Memory requests/limits is required for HPA to function
resources:
  requests:
    cpu: "250m"
    memory: "768Mi"
  limits:
    cpu: "500m"
    memory: "1536Mi"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

probes:
  liveness:
    httpGet:
      path: /
      port: 8001
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    httpGet:
      path: /
      port: 8001
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

ingress:
  # Define the domain name for the Ingress host rule
  host: "oag-status-page-devops.site"
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: "ofek-status-page-alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    # Enable HTTPS and HTTP to HTTPS redirect
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    # Attach the ACM certificate ARN we just generated
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:992382545251:certificate/19be50f7-f93f-46af-9ce1-31f68bbb4a1f"