# Default configuration values for the Status Page application.
# These values will be injected into our Kubernetes templates.

# Number of pod replicas we want running for high availability
replicaCount: 3

# Docker image details from Amazon ECR
image:
  repository: "992382545251.dkr.ecr.us-east-1.amazonaws.com/ofek-status-page-repo"
  pullPolicy: Always
  tag: "v1.0.0" # The specific version your friend uploaded


# PostgreSQL Database (RDS) configuration
database:
  host: "ofek-status-page-rds.cx248m4we6k7.us-east-1.rds.amazonaws.com"
  port: "5432"
  name: "statuspagedb"

# Redis Cache (ElastiCache) configuration
redis:
  host: "ofek-status-page-redis.7fftml.0001.use1.cache.amazonaws.com"
  port: "6379"

# S3 Bucket configuration for static assets
s3:
  bucketName: "ofek-status-page-assets-bucket-8849"
  region: "us-east-1"

# Internal service port for the application
service:
  port: 8001

  # Defining CPU and Memory requests/limits is required for HPA to function
resources:
  requests:
    cpu: "250m"
    memory: "768Mi"
  limits:
    cpu: "500m"
    memory: "1536Mi"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

probes:
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 3
ingress:
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: "ofek-status-page-alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"