name: CI Pipeline

on: [push]

env:
  PYTHON_VERSION: '3.10'
  # נתיבים מלאים מהשורש של ה-Repository
  REQUIREMENTS_PATH: 'app/requirements.txt'
  MANAGE_PY_PATH: 'app/statuspage/manage.py'
  # פקודת הבדיקה משתמשת בנתיב המלא לקובץ ה-manage.py
  CHECK_COMMAND: 'python app/statuspage/manage.py check'
  
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository 📂
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }} 🐍
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies 🛠️
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.REQUIREMENTS_PATH }}

      - name: Run System Checks ✅
        run: ${{ env.CHECK_COMMAND }}
