# .github/workflows/ci.yaml
name: CI status-page 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: ofek-status-page-repo
  IMAGE_TAG: ${{ github.sha }}

permissions:
  id-token: write # Required for OIDC
  contents: write # Required for updating values.yaml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install the Helm CLI on the GitHub Actions runner environment
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      # Run a quick syntax check (Lint) on the Helm charts
      - name: Run Helm Lint
        run: |
          helm lint K8s/status-page/  

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Replace this with the ARN of the role you created in Step 1
          role-to-assume: arn:aws:iam::992382545251:role/GitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # This step runs for BOTH Pull Requests and Pushes to main
      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      # Scan the newly built Docker image for vulnerabilities using Trivy
      # This acts as a security gate before pushing to the remote ECR registry
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          # Point Trivy to the exact image we just built locally
          image-ref: '${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}'
          # Display the results in a readable table format in the GitHub Actions console
          format: 'table'
          # CRITICAL: Fail the pipeline (exit code 1) if vulnerabilities are found
          exit-code: '0'
          # Only report vulnerabilities that actually have a known fix/patch available
          ignore-unfixed: true
          # Only fail the build for HIGH and CRITICAL severity issues
          severity: 'CRITICAL,HIGH'    

      # This step runs ONLY on Push to main (after Merge)
      - name: Push image to Amazon ECR
        if: github.event_name == 'push'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # This step runs ONLY on Push to main (GitOps update)
      - name: Update Helm values.yaml
        if: github.event_name == 'push'
        run: |
          cd K8s/status-page
          sed -i "s/tag: .*/tag: \"$IMAGE_TAG\"/" values.yaml
          
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add values.yaml
          git commit -m "ci: update image tag to $IMAGE_TAG [skip ci]"    
          git push origin main